### ISSUE TITLE
Profile Not Working

### ISSUE THREAD

**Issue by nickhou75** [itxve/fetch-clash-node#1]
The proflie has vless proxy. It does not make Clash work properly. How to rectfy the profile? thanks a lot.

![image](https://github.com/itxve/fetch-clash-node/assets/91721613/430e2280-ef4c-4e81-93a7-a5f27c1d0e8e)

**Comment by itxve** [comment]
Maybe you can manually delete lines of type `vless`

**Comment by nickhou75** [comment]
I copied and deleted vless node in '.txt' file format. Then I changed '.txt' into '.yaml'. It is still not working.
![image](https://github.com/itxve/fetch-clash-node/assets/91721613/89943310-b9ad-46d8-842b-52ab80ce9a80)
