### ISSUE TITLE
举例解答：如何合并多个订阅链接

### ISSUE THREAD

**Issue by jacobin** [itxve/fetch-clash-node#3]
譬如有多个订阅链接如下：

> https://www.abc.com/def.yaml
> https://www.ghi.com/jkl.txt
> https://www.mno.com/pqr.b64

则，用『**|**』把它们连结在一起得如下结果URLs

> https://www.abc.com/def.yaml|https://www.ghi.com/jkL.txt|https://www.mno.com/pqr.b64

注意，其中的『**|**』两侧不要留有空格。
以浏览器打开如下网站

> https://www.urlencoder.org/

把URLs填入其中并进行编码得如下结果ENCODED

> https%3A%2F%2Fwww.abc.com%2Fdef.yaml%7Chttps%3A%2F%2Fwww.ghi.com%2FjkL.txt%7Chttps%3A%2F%2Fwww.mno.com%2Fpqr.b64

最后，在对subconverter的调用中就可以如下格式得以进行

> http://127.0.0.1:25500/sub?target=clash&url=https%3A%2F%2Fwww.abc.com%2Fdef.yaml%7Chttps%3A%2F%2Fwww.ghi.com%2FjkL.txt%7Chttps%3A%2F%2Fwww.mno.com%2Fpqr.b64

**Comment by itxve** [comment]
谢谢解答，多个订阅链接已合并
